### ISSUE TITLE
RF-01: Construir dataset propio

### ISSUE THREAD

**Issue by pparramen** [pparramen/uvlhub#1]
El sistema debe permitir a los usuarios seleccionar modelos específicos de los datasets disponibles y descargarlos como un conjunto. Si el usuario está autenticado, también puede cargar dicho conjunto de modelos como un dataset personal.

**Comment by benavidescuevas** [comment]
Please, remember to write your code in English. Comments can be done in Spanish if you want, but the code should be in English.
